[workspace]
resolver = "2"
members = [
  "ark",
  "ark-contracts",
  "ark-db",
  "ark-repo",
  "ark-web",
  "ark-web3",
  "ark-web-common",
  "coinflip",
  "coinflip-contracts",
  "coinflip-repo",
  "coinflip-web",
  "libs/ark-utils",
  "libs/crypto-compare"
]