version: "3.9"

services:
  postgres:
    container_name: ark
    image: "postgres:14"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin_password"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
