version: "3.9"

services:
  postgres:
    container_name: ark-db
    image: "postgres:14"
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
